id: D73EBAF3E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:36:46+00:00'
last_modified: '2022-05-26T10:12:26.587127+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    acc8:
      image_group_id: I1PD95863
      title: སྤྱོད་པ་བསྡུས་པའི་སྒྲོན་མ།
      total_pages: 1634
      order: 18
      base_file: acc8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
