id: 639c2f4b462d421e80f83a76b7d2dd8a
initial_creation_type: ocr
source_metadata:
  volumes:
    f1ed4aad587e439d94323d5e49364c72:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: སྤྱོད་པ་བསྡུས་པའི་སྒྲོན་མ།
      total_pages: 1634
      volume_number: 18
